# Generated by Django 4.2.16 on 2024-09-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(default="0000000000000", max_length=13),
        ),
    ]
