# Generated by Django 5.1.1 on 2024-09-26 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookQuantity',
            fields=[
                ('book_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='book_id', serialize=False, to='book_app.book')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=10),
        ),
    ]
