# Generated by Django 5.1.1 on 2024-09-26 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_bookquantity_alter_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookquantity',
            old_name='book_id',
            new_name='book',
        ),
    ]
