# Generated by Django 4.2.16 on 2024-09-23 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0002_book_isbn"),
        ("book_app", "0003_book_quantity"),
    ]

    operations = []
